---
- hosts: webservers
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: copy index.html  
      copy: src=/tmp/index.html dest=/var/www/html/ mode=0644
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted 
